# Wokflow para baixar dados abertos da ANAC a cada dia (08 UTC)

name: flat-data-anac
on:
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
  schedule:
    - cron: 0 8 * * 1-5
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
        
# URL dos dados a serem baixados (http_url) e on nomes dos arquivos (downloaded_filename)        
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://sistemas.anac.gov.br/dadosabertos/Aeronaves/drones%20cadastrados/SISANT.json
          downloaded_filename: drones.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://sistemas.anac.gov.br/dadosabertos/Aeronaves/RAB/dados_aeronaves.json
          downloaded_filename: aeronaves.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://sistemas.anac.gov.br/dadosabertos/Aerodromos/Lista%20de%20aer%C3%B3dromos%20privados/Aerodromos%20Privados/AerodromosPrivados.json
          downloaded_filename: aerodromos-privados.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://sistemas.anac.gov.br/dadosabertos/Aerodromos/Lista%20de%20aer%C3%B3dromos%20p%C3%BAblicos/AerodromosPublicos.json
          downloaded_filename: aerodromos-publicos.json
# muito grande     - name: Fetch data
#        uses: githubocto/flat@v3
#        with:
#          http_url: https://sistemas.anac.gov.br/dadosabertos/Gestao%20Interna/Manifestacoes%20de%20Usuarios/ManifestacaoDeUsuarios.json
#          downloaded_filename: manifestacoes-de-usuarios.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://sistemas.anac.gov.br/dadosabertos/Gestao%20Interna/Pesquisa%20de%20Servi%C3%A7os/PesquisaServicos.json
          downloaded_filename: pesquisa-de-servicos.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://sistemas.anac.gov.br/dadosabertos/Gestao%20Interna/Lista%20de%20TFAC/Lista_TFAC.json
          downloaded_filename: tfac-lista.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://sistemas.anac.gov.br/dadosabertos/Organiza%C3%A7%C3%B5es%20de%20Forma%C3%A7%C3%A3o/Escolas%20da%20Avia%C3%A7%C3%A3o%20Civil/Escolas.json
          downloaded_filename: escolas.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://sistemas.anac.gov.br/dadosabertos/Organiza%C3%A7%C3%B5es%20de%20Forma%C3%A7%C3%A3o/Escolas%20da%20Avia%C3%A7%C3%A3o%20Civil/Cursos.json
          downloaded_filename: cursos.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://sistemas.anac.gov.br/dadosabertos/Organiza%C3%A7%C3%B5es%20de%20Manuten%C3%A7%C3%A3o/Oficinas%20de%20Manuten%C3%A7%C3%A3o/OrganizacoesDeManutencao.json
          downloaded_filename: oficinas.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://sistemas.anac.gov.br/dadosabertos/Pessoal%20da%20Avia%C3%A7%C3%A3o%20Civil/Profissionais%20Credenciados/ProfissionaisCredenciados.json
          downloaded_filename: profissionais-credenciados.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://sistemas.anac.gov.br/dadosabertos/Seguranca%20Operacional/Ocorrencia/V_OCORRENCIA_AMPLA.json
          downloaded_filename: safety-ocorrencias.json
# muito grande     - name: Fetch data
#        uses: githubocto/flat@v3
#        with:
#          http_url: https://sistemas.anac.gov.br/dadosabertos/Voos%20e%20opera%C3%A7%C3%B5es%20a%C3%A9reas/Dados%20do%20consumidor.gov/DadosDoConsumidor2020.json
#          downloaded_filename: consumidor-gov-2020.json
# muito grande     - name: Fetch data
#        uses: githubocto/flat@v3
#        with:
#          http_url: https://sistemas.anac.gov.br/dadosabertos/Voos%20e%20opera%C3%A7%C3%B5es%20a%C3%A9reas/Dados%20do%20consumidor.gov/DadosDoConsumidor2019.json
#          downloaded_filename: consumidor-gov-2019.json
# muito grande     - name: Fetch data
#        uses: githubocto/flat@v3
#        with:
#          http_url: https://sistemas.anac.gov.br/dadosabertos/Voos%20e%20opera%C3%A7%C3%B5es%20a%C3%A9reas/Dados%20Estat%C3%ADsticos%20do%20Transporte%20A%C3%A9reo/Dados_Estatisticos.csv
#          downloaded_filename: dados-estatisticos-transporte-aereo.json        
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://sistemas.anac.gov.br/dadosabertos/fiscalizacao/Lista%20de%20processos%20administrativos%20sancionadores/ListaDeProcessosAdministrativosSancionadores.json
          downloaded_filename: processos-administrativos-sancionadores.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://sistemas.anac.gov.br/dadosabertos/fiscalizacao/Opera%C3%A7%C3%B5es%20de%20fiscaliza%C3%A7%C3%A3o/fiscalizacoes.json
          downloaded_filename: fiscalizacoes.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://sistemas.anac.gov.br/dadosabertos/regulamentacao/cesc-condicao-especial/cesc-condicao-especial.json
          downloaded_filename: condicao-especial.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://sistemas.anac.gov.br/dadosabertos/regulamentacao/iac-e-is/is.json
          downloaded_filename: is.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://sistemas.anac.gov.br/dadosabertos/regulamentacao/iac-e-is/iac.json
          downloaded_filename: iac.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://sistemas.anac.gov.br/dadosabertos/regulamentacao/rbha-e-rbac/rbac.json
          downloaded_filename: rbac.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://sistemas.anac.gov.br/dadosabertos/regulamentacao/rbha-e-rbac/rbha.json
          downloaded_filename: rbha.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://sistemas.anac.gov.br/dadosabertos/regulamentacao/planos-e-programas/planos-e-programas.json
          downloaded_filename: planos-e-programas.json
